# Generated by Django 2.1 on 2019-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_remove_studentsgroup_students'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='academy.StudentsGroup'),
        ),
    ]
