# Generated by Django 2.1 on 2019-05-14 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0003_assignmentreview_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentreview',
            name='assignment_activity',
        ),
        migrations.RemoveField(
            model_name='assignmentreview',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='students',
        ),
        migrations.AddField(
            model_name='assignmentactivity',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentactivity',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssignmentReview',
        ),
    ]
