# Generated by Django 2.1 on 2019-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20190514_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysupportmaterial',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitysupportmaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='supportmaterial',
            name='activity',
            field=models.ManyToManyField(to='academy.Activity'),
        ),
        migrations.AddField(
            model_name='supportmaterial',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supportmaterial',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActivitySupportMaterial',
        ),
    ]
