# Generated by Django 2.1 on 2019-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20190514_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentactivity',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
