# Generated by Django 2.1 on 2019-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_assignmentactivity_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmaterial',
            name='material_type',
            field=models.CharField(choices=[('0', 'Link'), ('1', 'File'), ('2', 'Video')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='supportmaterial',
            name='material_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
