# Generated by Django 2.1 on 2019-05-26 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0007_auto_20190524_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('file_assignment', models.FileField(blank=True, null=True, upload_to='assignment_files/')),
                ('url_assignment', models.URLField(blank=True, null=True)),
                ('delivered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='file_assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assignmentactivity',
            name='url_assignment',
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='assignment_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_deliveries', to='academy.AssignmentActivity'),
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentactivity',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='academy.StudentsGroup'),
            preserve_default=False,
        ),
    ]
