# Generated by Django 2.1 on 2019-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20190526_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentactivity',
            options={'verbose_name': 'Assignment activity', 'verbose_name_plural': 'Assignemnts activities'},
        ),
        migrations.AlterModelOptions(
            name='assignmentdelivery',
            options={'verbose_name': 'Assignment delivery', 'verbose_name_plural': 'Assignment deliveries'},
        ),
        migrations.AddField(
            model_name='studentsgroup',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
