# Generated by Django 2.1 on 2019-05-27 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20190526_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsgroup',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
