# Generated by Django 2.1 on 2019-05-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20190527_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('reviewed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignmentdelivery',
            name='score',
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='anotation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreview',
            name='assignment_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_reviews', to='academy.AssignmentDelivery'),
        ),
    ]
