# Generated by Django 2.1 on 2019-05-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_auto_20190528_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreview',
            name='assignment_delivery',
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='reviewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DeliveryReview',
        ),
    ]
