# Generated by Django 2.1 on 2019-05-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_auto_20190528_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmaterial',
            name='material_type',
            field=models.CharField(choices=[('0', 'Link'), ('1', 'File')], default='0', max_length=1),
        ),
    ]
