# Generated by Django 2.1 on 2019-05-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_auto_20190528_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmaterial',
            name='material_type',
        ),
    ]
