# Generated by Django 2.1 on 2019-05-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_remove_supportmaterial_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentdelivery',
            old_name='url_assignment',
            new_name='delivery_url',
        ),
        migrations.RemoveField(
            model_name='assignmentdelivery',
            name='file_assignment',
        ),
        migrations.AddField(
            model_name='assignmentdelivery',
            name='delivery_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_files/'),
        ),
    ]
